#!/bin/bash

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"
CONTAINER="dockermigrator"

case "$1" in
start)
    # do nothing, docker application will be started by appcenter
    exit 0
    ;;
stop)
    # do nothing, docker application will be stopped by appcenter
    exit 0
    ;;
status)
    st="$(docker inspect --format '{{.State.Status}}' "$CONTAINER" 2>/dev/null || true)"
    [ "$st" = "running" ] && exit 0
    exit 3
    ;;
*)
    exit 1
    ;;
esac
