name: dockermigrator

services:
  dockermigrator:
    build: .
    image: dockermigrator:latest
    container_name: dockermigrator
    restart: unless-stopped
    networks:
      - trim-default
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${wizard_docker_root:-/vol1/1000/docker}:${wizard_docker_root:-/vol1/1000/docker}
    environment:
      - TZ=Asia/Shanghai
      - LOCAL_DOCKER_ROOT=${wizard_docker_root:-/vol1/1000/docker}

networks:
  trim-default:
    external: true
